name: Django CI

on:
  push:
    branches: [ "591broadcast" ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        pip install requests==2.28.1
        pip install beautifulsoup4==4.12.2
        pip install emoji==2.2.0
        pip install selenium==4.24.0

    - name: Run tests
      run: python 591.py
